name: mtgCollectionFE
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches: [ "main" ]
    
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            echo ${{secrets.ENV}} > .env.production
        - run: flyctl deploy --remote-only